# Generated by Django 2.1.7 on 2019-04-03 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190327_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('project_type', models.CharField(blank=True, max_length=128)),
                ('institutions', models.TextField(blank=True)),
                ('pmf_status', models.CharField(blank=True, max_length=128)),
                ('start_year', models.PositiveIntegerField(blank=True)),
                ('duration', models.PositiveIntegerField(blank=True)),
                ('project_manager', models.CharField(blank=True, max_length=128)),
                ('web_site', models.CharField(blank=True, max_length=128)),
                ('contact_person', models.CharField(blank=True, max_length=128)),
                ('pmf_project_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Profile')),
            ],
        ),
    ]
