# Generated by Django 2.1.7 on 2019-04-03 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190403_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pmf_project_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
    ]
