# Generated by Django 2.1.7 on 2019-04-04 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190403_1224'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Membership',
            new_name='ProjectMembership',
        ),
        migrations.AlterUniqueTogether(
            name='projectmembership',
            unique_together={('profile', 'project', 'role')},
        ),
    ]
