# Generated by Django 2.1.7 on 2019-04-08 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190404_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('key_words', models.CharField(blank=True, max_length=255)),
                ('research_direction', models.TextField(blank=True)),
                ('group_leader', models.CharField(blank=True, max_length=255)),
                ('members', models.TextField(blank=True)),
                ('goals', models.TextField(blank=True)),
                ('equipment', models.TextField(blank=True)),
                ('cooperation', models.TextField(blank=True)),
                ('web_site', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='research_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ResearchGroup'),
        ),
    ]
