# Generated by Django 2.1.7 on 2019-04-09 08:34

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190408_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchgroup',
            name='contact_person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
        migrations.AddField(
            model_name='researchgroup',
            name='img_1',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.path),
        ),
        migrations.AddField(
            model_name='researchgroup',
            name='img_2',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.path),
        ),
        migrations.AddField(
            model_name='researchgroup',
            name='img_3',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.path),
        ),
        migrations.AddField(
            model_name='researchgroup',
            name='img_4',
            field=models.ImageField(blank=True, null=True, upload_to=api.models.path),
        ),
    ]
