# Generated by Django 2.1.7 on 2019-04-09 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190409_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchgroup',
            name='contact_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Profile'),
        ),
    ]
